import uuid 
import enum
from datetime import datetime
from sqlalchemy import Integer,String, ForeignKey,JSON, DateTime, func, Text, Enum
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.ext.mutable import MutableList
from typing import TYPE_CHECKING
from app.db.base import Base

if TYPE_CHECKING:
    from app.models.user import User

class ExplanationMode(str, enum.Enum):
    CONCISE = "concise"
    BEGINNER = "beginner"
    DETAILED = "detailed"


class Explanation(Base):
    __tablename__ = "explanation"
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # Info received from extension
    selected_text: Mapped[str] = mapped_column(
        Text,
        nullable=False
    )
    surrounding_context: Mapped[str | None] = mapped_column(
        Text,
        nullable=True
    )
    page_title: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True
    )
    page_url: Mapped[str | None] = mapped_column(
        Text,
        nullable=True
    )

    mode: Mapped[ExplanationMode] = mapped_column(
        Enum(
            ExplanationMode,
            name="explanation_mode",
            values_callable=lambda enum_class: [
                member.value for member in enum_class
            ],
        ),
        nullable=False,
    )

    # Generated by LLM

    summary: Mapped[str] = mapped_column(
        Text,
        nullable=False
    )
    explanation: Mapped[str] = mapped_column(
        Text,
        nullable=False
    )
    key_points: Mapped[list[str]] = mapped_column(
        MutableList.as_mutable(JSONB),
        nullable=False,
        default=list,
    )
    example:Mapped[str | None] = mapped_column(
        Text,
        nullable=True
    )
    analogy: Mapped[str | None] = mapped_column(
        Text,
        nullable=True
    )
    # code_content: dtype? 

    # LLM Tracking info
    model_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    input_tokens:Mapped[int | None] = mapped_column(
        Integer,
        nullable=True
    )
    output_tokens:Mapped[int | None] = mapped_column(
        Integer,
        nullable=True
    )

    latency_ms: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False
    )

    user: Mapped["User"] = relationship(back_populates="explanations")

